#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const outputDir = path.join(__dirname, 'output');

// Desired section order for LaTeX
const TEX_SECTION_ORDER = ['Work', 'Skills', 'Education', 'Certificates'];

function reorderTexSections(content) {
  // Extract everything before first \section and after \end{document}
  const preMatch = content.match(/^([\s\S]*?)\\section\{/);
  const postMatch = content.match(/(\\end\{document\}[\s\S]*)$/);
  if (!preMatch || !postMatch) return content;

  const preamble = preMatch[1];
  const ending = postMatch[1];

  // Extract each \section{...} block
  const sectionRegex = /\\section\{([^}]+)\}([\s\S]*?)(?=\\section\{|\\end\{document\})/g;
  const sections = {};
  let match;
  while ((match = sectionRegex.exec(content)) !== null) {
    sections[match[1]] = '\\section{' + match[1] + '}' + match[2];
  }

  // Rebuild in desired order
  let reordered = preamble;
  for (const name of TEX_SECTION_ORDER) {
    if (sections[name]) {
      reordered += sections[name];
      delete sections[name];
    }
  }
  // Append any remaining sections not in our order list
  for (const name of Object.keys(sections)) {
    reordered += sections[name];
  }
  reordered += ending;

  return reordered;
}

for (const file of fs.readdirSync(outputDir)) {
  const ext = path.extname(file);
  if (!['.html', '.md', '.tex'].includes(ext)) continue;

  const filePath = path.join(outputDir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  const before = content;

  // Remove "Generated by yamlresume" lines
  content = content.replace(/.*[Gg]enerated\s+(by|with)\s+yamlresume.*/gi, '');

  // LaTeX: replace fonts and remove CJK support
  // Remove Linux Libertine font blocks
  content = content.replace(/\\IfFontExistsTF\{Linux Libertine[^}]*\}\{[^}]*\}\{[^}]*\}\n?/g, '');
  // Remove CJK/ctex package and font config
  content = content.replace(/%% CTeX[\s\S]*?\\setCJKsansfont\{[^}]*\}\n\}\{\}\n/g, '');
  // Set clean cross-platform fonts (Helvetica for sans, Georgia for serif)
  content = content.replace(
    /\\usepackage\{fontspec\}\n/,
    '\\usepackage{fontspec}\n' +
    '\\setmainfont{Helvetica}\n' +
    '\\setsansfont{Helvetica}\n'
  );
  // Shrink name and title to fit on one line
  content = content.replace(
    /\\begin\{document\}/,
    '\\renewcommand*{\\namefont}{\\fontsize{16}{19}\\mdseries\\upshape}\n' +
    '\\renewcommand*{\\titlefont}{\\fontsize{16}{19}\\mdseries\\upshape}\n' +
    '% Put title and company on same line, years on right\n' +
    '\\renewcommand*{\\cventry}[7][.25em]{\n' +
    '  \\cvitem[#1]{}{\n' +
    '    {\\bfseries#3} -- {\\itshape#4}\\hfill{\\small\\color{gray}#2}\\strut\n' +
    '    \\ifx&#7&\\else{\\\\\\small#7}\\fi\n' +
    '  }\n' +
    '  \\vspace{0.6em}\n' +
    '}\n\n' +
    '\\begin{document}'
  );

  // Bold numbers with metric suffixes in tex (e.g., 13x, 50%, 8bn+, 2,500+)
  if (ext === '.tex') {
    // Match optional \$ prefix, digits, then metric suffix
    content = content.replace(
      /(\\?\$?\d[\d,.]*(?:x|\\?%|bn|k)\+?)/g,
      (m) => '\\textbf{' + m + '}'
    );
    // Also bold "number+" patterns like "2000+", "100+"
    content = content.replace(
      /(?<!\\textbf\{)(\\?\$?\d[\d,.]*\+)(?!\})/g,
      (m) => '\\textbf{' + m + '}'
    );
  }

  // Fix double https:// in homepage link
  content = content.replace(/\\homepage\{https:\/\//, '\\homepage{');

  // Swap certificate name and issuer in Certificates section
  content = content.replace(
    /(\\section\{Certificates\}[\s\S]*?)(?=\\section\{|\\end\{document\})/g,
    (certBlock) => {
      return certBlock.replace(
        /\\cventry\{([^}]*)\}\s*\{([^}]*)\}\s*\{([^}]*)\}/g,
        '\\cventry{$1}\n        {$3}\n        {$2}'
      );
    }
  );

  // Remove Languages section entirely
  content = content.replace(/\\section\{Languages\}[\s\S]*?(?=\\section\{|\\end\{document\})/g, '');

  // Remove "Basics" section header — summary should stand on its own
  content = content.replace(/\\section\{Basics\}\n\n/g, '');                // LaTeX
  content = content.replace(/<h2[^>]*>Basics<\/h2>\n?/gi, '');              // HTML
  content = content.replace(/^## Basics\n\n/gm, '');                        // Markdown

  // Reorder LaTeX sections
  if (ext === '.tex') {
    content = reorderTexSections(content);
  }

  // Clean up extra blank lines
  content = content.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';

  if (content !== before) {
    fs.writeFileSync(filePath, content);
    console.log(`Post-processed ${file}`);
  }
}
